### ISSUE TITLE
Support for on-prem provider

### ISSUE THREAD

**Issue by writeClearly** [redkubes/quickstart#16]
I saw that you deleted the on-premises provider in 8906a2c1de11507076690ed9eb333334ad23d840, what was the reason behind that? 
I am looking for some production-ready Kubernetes config, but mostly for prototyping and local testing.
I wish to dabble a little locally before deploying it in a cloud. 
Is it possible to test it locally without a great hassle?

**Comment by diabhey** [comment]
Hi @writeClearly: The team is working on a new release that will make most of the applications (optional) thereby reducing the footprint of Otomi. By doing this we make installing on your local cluster easier. I would suggest waiting for the new release but if you want to try it out now, I can help you with it. Can you join our slack channel so that we can get in touch with you? Here you can find the link tour channel: https://redkubes.com/community/

**Comment by writeClearly** [comment]
Wow, I did not expect that, thank you for your offer. It's great to hear that you keep improving Otomi's features. 
I wouldn't like to increase your workload in the backlog so I will wait for the release patiently or dabble with git history if rushed.
Good luck ;)
(If this issue decrease your organization metrics feel free to close)

**Comment by diabhey** [comment]
I will keep you in the loop. Thank you for your support :)

**Comment by diabhey** [comment]
@writeClearly : As promised, you can now install Otomi on minikube(Mac/Windows) and also on cloud providers such as DigitalOcean and Linode. Feel free to check it out and get back to us in case of any questions or suggestions. We look forward to hearing back from you.
